- hosts: Standalone:overcloud
  strategy: tripleo_free
  name: Server network validation
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  tasks:

    - name: Basic Network Validation
      include_role:
        name: tripleo_nodes_validation
      vars:
        tripleo_nodes_validation_validate_controllers_icmp: "{{ validate_controllers_icmp }}"
        tripleo_nodes_validation_validate_gateway_icmp: "{{ validate_gateways_icmp }}"
        tripleo_nodes_validation_validate_fqdn: "{{ validate_fqdn }}"
        tripleo_nodes_validation_ping_test_ips: "{{ ping_test_ips.get(tripleo_role_name, '').split() | list | unique }}"
        tripleo_nodes_validation_ping_test_gateway_ips: "{{ ping_test_gateway_ips.get(tripleo_role_name, []) }}"
  tags:
    - overcloud
    - pre_deploy_steps
    - network_deploy_steps
