- hosts: Undercloud
  strategy: tripleo_linear
  name: External deployment Post Deploy tasks
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  become: false
  vars:
    bootstrap_server_id: 8e1ea7ca-3a29-4bb7-acd5-0d40a9d18d89
    deploy_identifier: 1657771405
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - name: External deployment Post Deploy tasks
      delegate_to: localhost
      run_once: true
      debug:
        msg: Use --start-at-task 'External deployment Post Deploy tasks' to resume from this task
    - import_tasks: external_post_deploy_steps_tasks.yaml
  tags:
    - external
    - external_deploy_steps
    - external_post_deploy_steps
