- hosts: Standalone:overcloud
  strategy: tripleo_free
  name: Overcloud container setup tasks
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  vars:
    bootstrap_server_id: 13dd0e41-d565-4626-8040-9e169a8e548a
    deploy_identifier: 1658205425
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - name: Overcloud container setup tasks
      block:
        - name: Overcloud container setup tasks
          delegate_to: localhost
          run_once: true
          debug:
            msg: Use --start-at-task 'Overcloud container setup tasks' to resume from this task
        - name: Write config data
          include_tasks: common_container_setup_tasks.yaml
          when:
            - (deploy_identifier is defined and deploy_identifier != "" and deploy_identifier is not none)
  tags:
    - overcloud
    - container_setup_tasks
