- hosts: Standalone:overcloud
  strategy: tripleo_free
  name: Host prep steps
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  vars:
    bootstrap_server_id: 2e07649e-027d-4f3e-a48d-e2b820d42375
    deploy_identifier: 1658202097
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:

    - name: Deploy Artifacts
      tripleo_push_artifacts:
        artifact_urls: "{{ deploy_artifact_urls | default([]) }}"
        artifact_paths: "{{ deploy_artifact_files | default([]) }}"
      when:
        - ((deploy_artifact_urls | default([]) | length) > 0) or
          ((deploy_artifact_files | default([]) | length) > 0)

    - name: Standalone Host prep block
      when:
        - tripleo_role_name == 'Standalone'
      block:
        - name: Standalone Host prep steps
          delegate_to: localhost
          run_once: true
          debug:
            msg: Use --start-at-task 'Standalone Host prep steps' to resume from this task
        - include_tasks: Standalone/host_prep_tasks.yaml
    - name: Compute Host prep block
      when:
        - tripleo_role_name == 'Compute'
      block:
        - name: Compute Host prep steps
          delegate_to: localhost
          run_once: true
          debug:
            msg: Use --start-at-task 'Compute Host prep steps' to resume from this task
        - include_tasks: Compute/host_prep_tasks.yaml
  tags:
    - overcloud
    - host_prep_steps
