- hosts: overcloud
  strategy: tripleo_linear
  name: Common roles for TripleO servers
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  # pre_tasks run before any roles in a play, so we use it for the
  # named debug task for --start-at-task.
  pre_tasks:
    - name: Common roles for TripleO servers
      delegate_to: localhost
      run_once: true
      debug:
        msg: Use --start-at-task 'Common roles for TripleO servers' to resume from this task
  tasks:
    - include_role:
        name: tripleo_bootstrap
    - include_role:
        name: tripleo_ssh_known_hosts
  tags:
    - common_roles
