- hosts: Undercloud
  strategy: tripleo_free
  name: External deployment step 0
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  become: false
  vars:
    step: 0
    enable_debug: False
  tasks:
    - name: External deployment step 0
      delegate_to: localhost
      run_once: true
      debug:
        msg: Use --start-at-task 'External deployment step 0' to resume from this task
    - include_tasks: "external_deploy_steps_tasks_step0.yaml"
      when:
        - playbook_dir ~ '/external_deploy_steps_tasks_step0.yaml' is exists
  tags:
    - external
    - external_deploy_steps
    - step0

- import_playbook: common_deploy_steps_playbooks.yaml
  vars:
    deploy_source_host: "Undercloud"
    deploy_target_host: "overcloud"
