- hosts: Standalone:overcloud
  strategy: tripleo_free
  name: Host prep steps
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  vars:
    bootstrap_server_id: 468c1ecd-2834-4507-ad3a-7a78138277e4
    deploy_identifier: 1667379345
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:

    - name: Host prep steps
      delegate_to: localhost
      run_once: true
      debug:
        msg: Use --start-at-task 'Host prep steps' to resume from this task
    - name: Deploy Artifacts
      tripleo_push_artifacts:
        artifact_urls: "{{ deploy_artifact_urls | default([]) }}"
        artifact_paths: "{{ deploy_artifact_files | default([]) }}"
      when:
        - ((deploy_artifact_urls | default([]) | length) > 0) or
          ((deploy_artifact_files | default([]) | length) > 0)
    - include_tasks: "{{ _task_file_path }}"
      vars:
        _task_file_path: "{{ tripleo_role_name }}/host_prep_tasks.yaml"
      when: "'{{ playbook_dir }}/{{ _task_file_path }}' is exists"
  tags:
    - overcloud
    - host_prep_steps
