- hosts: Standalone:overcloud
  strategy: tripleo_free
  name: Host prep steps
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  vars:
    bootstrap_server_id: 27bdcae3-b616-48cd-9be9-ae7cc76a5524
    deploy_identifier: 1662436537
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - name: Host prep steps
      delegate_to: localhost
      run_once: true
      debug:
        msg: Use --start-at-task 'Host prep steps' to resume from this task

    - name: Deploy Artifacts
      tripleo_push_artifacts:
        artifact_urls: "{{ deploy_artifact_urls | default([]) }}"
        artifact_paths: "{{ deploy_artifact_files | default([]) }}"
      when:
        - ((deploy_artifact_urls | default([]) | length) > 0) or
          ((deploy_artifact_files | default([]) | length) > 0)

    - name: Standalone Host prep tasks
      include_tasks: Standalone/host_prep_tasks.yaml
      when:
        - tripleo_role_name == 'Standalone'
    - name: Compute Host prep tasks
      include_tasks: Compute/host_prep_tasks.yaml
      when:
        - tripleo_role_name == 'Compute'
  tags:
    - overcloud
    - host_prep_steps
