- hosts: Standalone:overcloud
  strategy: tripleo_free
  name: Server network deployments
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  tasks:

    - name: Network Configuration
      delegate_to: localhost
      run_once: true
      debug:
        msg: Use --start-at-task 'Network Configuration' to resume from this task
    - name: Run Network Config
      import_role:
        name: tripleo_network_config
      vars:
        tripleo_network_config_update: "{{ network_config_update }}"
        tripleo_network_config_async_timeout: "{{ async_timeout | default(300) }}"
        tripleo_network_config_async_poll: "{{ async_poll | default(3) }}"
        tripleo_network_config_hide_sensitive_logs: false
        tripleo_network_config_legacy_script: false
        tripleo_network_config_safe_defaults: "{{ network_safe_defaults }}|bool"
  tags:
    - overcloud
    - pre_deploy_steps
    - network_deploy_steps
