- hosts: Standalone:overcloud
  strategy: tripleo_free
  name: Deploy step tasks for step 0
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  vars:
    bootstrap_server_id: 94b46769-dc39-45c4-ae16-322e8f615678
    step: 0
    deploy_identifier: 1662521648
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - import_tasks: deploy_steps_tasks_step_0.yaml
  tags:
    - overcloud
    - deploy_steps
    - step0
