- import_playbook: common_deploy_steps_playbooks.yaml
  vars:
    deploy_source_host: "Undercloud"
    deploy_target_host: "overcloud"
- hosts: Undercloud
  name: External update step 0
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  become: false
  vars:
    bootstrap_server_id: d7b3da1c-9415-4304-9f87-cdab820c5fce
    step: '0'
    deploy_identifier: 1658208171
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - import_tasks: external_update_steps_tasks.yaml
  tags:
    - step0
    - external
    - external_update_steps
- hosts: Undercloud
  name: External update step 1
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  become: false
  vars:
    bootstrap_server_id: d7b3da1c-9415-4304-9f87-cdab820c5fce
    step: '1'
    deploy_identifier: 1658208171
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - import_tasks: external_update_steps_tasks.yaml
  tags:
    - step1
    - external
    - external_update_steps
# putting both update and deploy tasks in the same
# playbook allows influencing the deploy tasks by
# variables "exported" from update tasks
- hosts: Undercloud
  name: External deploy step 1
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  become: false
  vars:
    bootstrap_server_id: d7b3da1c-9415-4304-9f87-cdab820c5fce
    step: '1'
    deploy_identifier: 1658208171
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - import_tasks: external_deploy_steps_tasks.yaml
  tags:
    - external
    - external_deploy_steps
    - step1
# putting both update and deploy tasks in the same
# playbook allows influencing the deploy tasks by
# variables "exported" from update tasks
- hosts: Undercloud
  name: External deploy step 2
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  become: false
  vars:
    bootstrap_server_id: d7b3da1c-9415-4304-9f87-cdab820c5fce
    step: '2'
    deploy_identifier: 1658208171
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - import_tasks: external_deploy_steps_tasks.yaml
  tags:
    - external
    - external_deploy_steps
    - step2
# putting both update and deploy tasks in the same
# playbook allows influencing the deploy tasks by
# variables "exported" from update tasks
- hosts: Undercloud
  name: External deploy step 3
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  become: false
  vars:
    bootstrap_server_id: d7b3da1c-9415-4304-9f87-cdab820c5fce
    step: '3'
    deploy_identifier: 1658208171
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - import_tasks: external_deploy_steps_tasks.yaml
  tags:
    - external
    - external_deploy_steps
    - step3
# putting both update and deploy tasks in the same
# playbook allows influencing the deploy tasks by
# variables "exported" from update tasks
- hosts: Undercloud
  name: External deploy step 4
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  become: false
  vars:
    bootstrap_server_id: d7b3da1c-9415-4304-9f87-cdab820c5fce
    step: '4'
    deploy_identifier: 1658208171
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - import_tasks: external_deploy_steps_tasks.yaml
  tags:
    - external
    - external_deploy_steps
    - step4
# putting both update and deploy tasks in the same
# playbook allows influencing the deploy tasks by
# variables "exported" from update tasks
- hosts: Undercloud
  name: External deploy step 5
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  become: false
  vars:
    bootstrap_server_id: d7b3da1c-9415-4304-9f87-cdab820c5fce
    step: '5'
    deploy_identifier: 1658208171
    enable_debug: False
    enable_puppet: True
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
    docker_puppet_debug: False
    docker_puppet_process_count: 6
    docker_puppet_mount_host_puppet: True
  tasks:
    - import_tasks: external_deploy_steps_tasks.yaml
  tags:
    - external
    - external_deploy_steps
    - step5
