- import_playbook: common_deploy_steps_playbooks.yaml
  vars:
    deploy_source_host: "Undercloud"
    deploy_target_host: "overcloud"
- hosts: overcloud
  strategy: tripleo_free
  any_errors_fatal: true
  tasks:
    - include_tasks: post_upgrade_steps_tasks.yaml
      with_sequence: start=0 end=3
      vars:
        bootstrap_server_id: 0cede55f-7f4c-417a-a263-fab755f2c09d
        deploy_identifier: 1657006753
        enable_debug: False
        enable_puppet: True
        container_cli: podman
        container_log_stdout_path: /var/log/containers/stdouts
        container_healthcheck_disabled: False
        docker_puppet_debug: False
        docker_puppet_process_count: 6
        docker_puppet_mount_host_puppet: True
      loop_control:
        loop_var: step
