- import_playbook: common_deploy_steps_playbooks.yaml
  vars:
    deploy_source_host: "Undercloud"
    deploy_target_host: "overcloud"
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 0
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  vars:
    bootstrap_server_id: 27bdcae3-b616-48cd-9be9-ae7cc76a5524
    step: '0'
    deploy_identifier: 1662436537
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:
    - include_tasks: Standalone/upgrade_tasks_step0.yaml
      when: tripleo_role_name == 'Standalone'
      tags:
        - always
    - include_tasks: Compute/upgrade_tasks_step0.yaml
      when: tripleo_role_name == 'Compute'
      tags:
        - always
  tags:
    - upgrade_steps
    - upgrade_step0
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 1
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  vars:
    bootstrap_server_id: 27bdcae3-b616-48cd-9be9-ae7cc76a5524
    step: '1'
    deploy_identifier: 1662436537
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:
    - include_tasks: Standalone/upgrade_tasks_step1.yaml
      when: tripleo_role_name == 'Standalone'
      tags:
        - always
    - include_tasks: Compute/upgrade_tasks_step1.yaml
      when: tripleo_role_name == 'Compute'
      tags:
        - always
  tags:
    - upgrade_steps
    - upgrade_step1
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 2
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  vars:
    bootstrap_server_id: 27bdcae3-b616-48cd-9be9-ae7cc76a5524
    step: '2'
    deploy_identifier: 1662436537
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:
    - include_tasks: Standalone/upgrade_tasks_step2.yaml
      when: tripleo_role_name == 'Standalone'
      tags:
        - always
    - include_tasks: Compute/upgrade_tasks_step2.yaml
      when: tripleo_role_name == 'Compute'
      tags:
        - always
  tags:
    - upgrade_steps
    - upgrade_step2
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 3
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  vars:
    bootstrap_server_id: 27bdcae3-b616-48cd-9be9-ae7cc76a5524
    step: '3'
    deploy_identifier: 1662436537
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:
    - include_tasks: Standalone/upgrade_tasks_step3.yaml
      when: tripleo_role_name == 'Standalone'
      tags:
        - always
    - include_tasks: Compute/upgrade_tasks_step3.yaml
      when: tripleo_role_name == 'Compute'
      tags:
        - always
  tags:
    - upgrade_steps
    - upgrade_step3
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 4
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  vars:
    bootstrap_server_id: 27bdcae3-b616-48cd-9be9-ae7cc76a5524
    step: '4'
    deploy_identifier: 1662436537
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:
    - include_tasks: Standalone/upgrade_tasks_step4.yaml
      when: tripleo_role_name == 'Standalone'
      tags:
        - always
    - include_tasks: Compute/upgrade_tasks_step4.yaml
      when: tripleo_role_name == 'Compute'
      tags:
        - always
  tags:
    - upgrade_steps
    - upgrade_step4
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 5
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  vars:
    bootstrap_server_id: 27bdcae3-b616-48cd-9be9-ae7cc76a5524
    step: '5'
    deploy_identifier: 1662436537
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:
    - include_tasks: Standalone/upgrade_tasks_step5.yaml
      when: tripleo_role_name == 'Standalone'
      tags:
        - always
    - include_tasks: Compute/upgrade_tasks_step5.yaml
      when: tripleo_role_name == 'Compute'
      tags:
        - always
  tags:
    - upgrade_steps
    - upgrade_step5
