- import_playbook: common_deploy_steps_playbooks.yaml
  vars:
    deploy_source_host: "Undercloud"
    deploy_target_host: "overcloud"
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 0
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  vars:
    bootstrap_server_id: 468c1ecd-2834-4507-ad3a-7a78138277e4
    step: '0'
    deploy_identifier: 1667379345
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:

    - include_tasks: "{{ _task_file_path }}"
      vars:
        _task_file_path: "{{ tripleo_role_name }}/upgrade_tasks_step{{ step }}.yaml"
      when: "'{{ playbook_dir }}/{{ _task_file_path }}' is exists"
      tags:
        - always

  tags:
    - upgrade_steps
    - upgrade_step0
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 1
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  vars:
    bootstrap_server_id: 468c1ecd-2834-4507-ad3a-7a78138277e4
    step: '1'
    deploy_identifier: 1667379345
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:

    - include_tasks: "{{ _task_file_path }}"
      vars:
        _task_file_path: "{{ tripleo_role_name }}/upgrade_tasks_step{{ step }}.yaml"
      when: "'{{ playbook_dir }}/{{ _task_file_path }}' is exists"
      tags:
        - always

  tags:
    - upgrade_steps
    - upgrade_step1
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 2
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  vars:
    bootstrap_server_id: 468c1ecd-2834-4507-ad3a-7a78138277e4
    step: '2'
    deploy_identifier: 1667379345
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:

    - include_tasks: "{{ _task_file_path }}"
      vars:
        _task_file_path: "{{ tripleo_role_name }}/upgrade_tasks_step{{ step }}.yaml"
      when: "'{{ playbook_dir }}/{{ _task_file_path }}' is exists"
      tags:
        - always

  tags:
    - upgrade_steps
    - upgrade_step2
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 3
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  vars:
    bootstrap_server_id: 468c1ecd-2834-4507-ad3a-7a78138277e4
    step: '3'
    deploy_identifier: 1667379345
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:

    - include_tasks: "{{ _task_file_path }}"
      vars:
        _task_file_path: "{{ tripleo_role_name }}/upgrade_tasks_step{{ step }}.yaml"
      when: "'{{ playbook_dir }}/{{ _task_file_path }}' is exists"
      tags:
        - always

  tags:
    - upgrade_steps
    - upgrade_step3
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 4
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  vars:
    bootstrap_server_id: 468c1ecd-2834-4507-ad3a-7a78138277e4
    step: '4'
    deploy_identifier: 1667379345
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:

    - include_tasks: "{{ _task_file_path }}"
      vars:
        _task_file_path: "{{ tripleo_role_name }}/upgrade_tasks_step{{ step }}.yaml"
      when: "'{{ playbook_dir }}/{{ _task_file_path }}' is exists"
      tags:
        - always

  tags:
    - upgrade_steps
    - upgrade_step4
- hosts: overcloud
  strategy: tripleo_free
  name: Upgrade tasks for step 5
  become: true
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: true
  vars:
    bootstrap_server_id: 468c1ecd-2834-4507-ad3a-7a78138277e4
    step: '5'
    deploy_identifier: 1667379345
    enable_debug: False
    container_cli: podman
    container_log_stdout_path: /var/log/containers/stdouts
    container_healthcheck_disabled: False
  tasks:

    - include_tasks: "{{ _task_file_path }}"
      vars:
        _task_file_path: "{{ tripleo_role_name }}/upgrade_tasks_step{{ step }}.yaml"
      when: "'{{ playbook_dir }}/{{ _task_file_path }}' is exists"
      tags:
        - always

  tags:
    - upgrade_steps
    - upgrade_step5
