collectd:
  collectd::plugin::memcached::instances:
    local:
      host:
      - 127.0.0.1
      - '%{lookup(''internal_api_uri'')}'
      port:
      - 11211
  collectd::plugin::virt::connection: qemu:///system
  tripleo.collectd.plugins.memcached:
  - memcached
  tripleo.collectd.plugins.nova_compute:
  - virt
horizon:
  get_attr:
  - NovaBase
  - role_data
  - service_config_settings
  horizon: null
  horizon::dashboards::heat::policies: {}
  horizon::dashboards::octavia::policies: {}
  horizon::policy::cinder_policies: {}
  horizon::policy::glance_policies: {}
  horizon::policy::keystone_policies: {}
  horizon::policy::neutron_policies: {}
mysql:
  cinder::db::mysql::dbname: cinder
  cinder::db::mysql::host: '%'
  cinder::db::mysql::password: KutXQeLq3w0rqwJUy5MwOowdU
  cinder::db::mysql::user: cinder
  glance::db::mysql::dbname: glance
  glance::db::mysql::host: '%'
  glance::db::mysql::password: IEhguPUe6OnKOeRjGPsC45Kp6
  glance::db::mysql::user: glance
  heat::db::mysql::dbname: heat
  heat::db::mysql::host: '%'
  heat::db::mysql::password: 8mye5b2UMQupCdoY2D8bvvl2g
  heat::db::mysql::user: heat
  keystone::db::mysql::dbname: keystone
  keystone::db::mysql::host: '%'
  keystone::db::mysql::password: iQUZJcaBGLDPIlVUi8UREjgtB
  keystone::db::mysql::user: keystone
  neutron::db::mysql::dbname: ovs_neutron
  neutron::db::mysql::host: '%'
  neutron::db::mysql::password: a1PIB0bVR8KCI5Nryq9ocVZeP
  neutron::db::mysql::user: neutron
  nova::db::mysql::dbname: nova
  nova::db::mysql::host: '%'
  nova::db::mysql::password: QgE5gYRM5zaHlZDihVfa0tiyC
  nova::db::mysql::user: nova
  nova::db::mysql_api::dbname: nova_api
  nova::db::mysql_api::host: '%'
  nova::db::mysql_api::password: QgE5gYRM5zaHlZDihVfa0tiyC
  nova::db::mysql_api::user: nova_api
  octavia::db::mysql::dbname: octavia
  octavia::db::mysql::host: '%'
  octavia::db::mysql::password: peshpcOkRNosh44C3XNwUGxtw
  octavia::db::mysql::persistence_dbname: octavia_persistence
  octavia::db::mysql::user: octavia
  placement::db::mysql::dbname: placement
  placement::db::mysql::host: '%'
  placement::db::mysql::password: vFwQ1AoetKNdWwCyrkEbcF6LS
  placement::db::mysql::user: placement
pacemaker:
  keystone::admin_password: 7i8YsihaRsvMJKyBxT2Z2RD3a
  keystone::endpoint::admin_url: http://192.168.1.25:35357
  keystone::endpoint::internal_url: http://192.168.1.25:5000
  keystone::endpoint::public_url: https://openstack.bne-home.net:13000
  keystone::endpoint::region: regionOne
rabbitmq:
  get_attr:
  - NovaBase
  - role_data
  - service_config_settings
  rabbitmq: null
rsyslog:
  tripleo_logging_sources_cinder_api:
  - file: /var/log/containers/cinder/cinder-api.log
    tag: openstack.cinder.api
  tripleo_logging_sources_cinder_scheduler:
  - file: /var/log/containers/cinder/cinder-scheduler.log
    tag: openstack.cinder.scheduler
  tripleo_logging_sources_cinder_volume:
  - file: /var/log/containers/cinder/cinder-volume.log
    tag: openstack.cinder.volume
  tripleo_logging_sources_glance_api:
  - file: /var/log/containers/glance/api.log
    tag: openstack.glance.api
  tripleo_logging_sources_haproxy:
  - file: /var/log/containers/haproxy/haproxy.log
    startmsg.regex: ^[a-zA-Z]{3} [0-9]{2} [:0-9]{8}
    tag: openstack.haproxy
  tripleo_logging_sources_heat_api:
  - file: /var/log/containers/heat/heat_api.log
    tag: openstack.heat.api
  tripleo_logging_sources_heat_api_cfn:
  - file: /var/log/containers/heat/heat_api_cfn.log
    tag: openstack.heat.api.cfn
  tripleo_logging_sources_heat_engine:
  - file: /var/log/containers/heat/heat-engine.log
    tag: openstack.heat.engine
  tripleo_logging_sources_horizon:
  - file: /var/log/containers/horizon/horizon.log
    tag: openstack.horizon
  tripleo_logging_sources_keystone:
    file: /var/log/containers/keystone/keystone.log
    tag: openstack.keystone
  tripleo_logging_sources_neutron_api:
  - file: /var/log/containers/neutron/server.log
    tag: openstack.neutron.api
  tripleo_logging_sources_nova_api:
  - file: /var/log/containers/nova/nova-api.log
    tag: openstack.nova.api
  tripleo_logging_sources_nova_compute:
  - file: /var/log/containers/nova/nova-compute.log
    tag: openstack.nova.compute
  tripleo_logging_sources_nova_conductor:
  - file: /var/log/containers/nova/nova-conductor.log
    tag: openstack.nova.conductor
  tripleo_logging_sources_nova_metadata:
  - file: /var/log/containers/nova/nova-metadata-api.log
    tag: openstack.nova.api.metadata
  tripleo_logging_sources_nova_scheduler:
  - file: /var/log/containers/nova/nova-scheduler.log
    tag: openstack.nova.scheduler
  tripleo_logging_sources_nova_vnc_proxy:
  - file: /var/log/containers/nova/nova-novncproxy.log
    tag: openstack.nova.vncproxy
  tripleo_logging_sources_octavia_api:
  - file: /var/log/containers/octavia/api.log
    tag: openstack.octavia.api
  tripleo_logging_sources_octavia_health_manager:
  - file: /var/log/containers/octavia/health-manager.log
    tag: openstack.octavia.health-manager
  tripleo_logging_sources_octavia_housekeeping:
  - file: /var/log/containers/octavia/housekeeping.log
    tag: openstack.octavia.housekeeping
  tripleo_logging_sources_octavia_worker:
  - file: /var/log/containers/octavia/worker.log
    tag: openstack.octavia.worker
  tripleo_logging_sources_pacemaker:
  - file: /var/log/pacemaker/pacemaker.log
    startmsg.regex: ^[a-zA-Z]{3} [0-9]{2} [:0-9]{8}
    tag: system.pacemaker
  tripleo_logging_sources_placement:
  - file: /var/log/containers/httpd/placement_wsgi_error_ssl.log
    tag: openstack.placement
