ContainerNovaComputeImage: quay.io/tripleowallaby/openstack-nova-compute:current-tripleo
ContainerNovaLibvirtConfigImage: quay.io/tripleowallaby/openstack-nova-compute:current-tripleo
ContainerNovaLibvirtImage: quay.io/tripleowallaby/openstack-nova-libvirt:current-tripleo
ContainerOvnControllerConfigImage: quay.io/tripleowallaby/openstack-ovn-controller:current-tripleo
ContainerOvnControllerImage: quay.io/tripleowallaby/openstack-ovn-controller:current-tripleo
compute_disable_irqbalance: false
compute_enable_ksm: false
container_cpuset_cpus: ''
neutron::agents::ovn_metadata::debug: false
neutron::agents::ovn_metadata::metadata_host: 192.168.1.25
neutron::agents::ovn_metadata::metadata_protocol: http
neutron::agents::ovn_metadata::metadata_workers: '8'
neutron::agents::ovn_metadata::ovsdb_connection_timeout: 180
neutron::agents::ovn_metadata::ovsdb_probe_interval: 60000
neutron::agents::ovn_metadata::shared_secret: tbSWhJKGivgVP7R2jav8YD9Cy
neutron::auth_strategy: keystone
neutron::core_plugin: ml2
neutron::db::database_db_max_retries: -1
neutron::db::database_max_retries: -1
neutron::db::sync::db_sync_timeout: 900
neutron::db::sync::extra_params: ''
neutron::dhcp_agent_notification: false
neutron::dns_domain: openstacklocal
neutron::global_physnet_mtu: 9000
neutron::host: '%{lookup(''fqdn_canonical'')}'
neutron::logging::debug: false
neutron::notification_driver:
- noop
neutron::purge_config: false
neutron::rabbit_heartbeat_in_pthread: false
neutron::rabbit_heartbeat_timeout_threshold: 60
neutron::report_interval: 300
neutron::rpc_response_timeout: 60
neutron::service_plugins:
- qos
- ovn-router
- trunk
- segments
- port_forwarding
- log
neutron::vlan_transparent: false
nfs_backend_enable: false
nfs_options: context=system_u:object_r:nfs_t:s0
nfs_share: ''
nfs_vers: '4.2'
nova::cache::backend: dogpile.cache.memcached
nova::cache::enabled: true
nova::cache::tls_enabled: false
nova::cinder::auth_type: v3password
nova::cinder::auth_url: http://192.168.1.25:5000/v3
nova::cinder::catalog_info: volumev3:cinderv3:internalURL
nova::cinder::cross_az_attach: true
nova::cinder::password: KutXQeLq3w0rqwJUy5MwOowdU
nova::cinder::project_name: service
nova::cinder::region_name: regionOne
nova::cinder::username: cinder
nova::compute::consecutive_build_service_disable_threshold: '10'
nova::compute::cpu_dedicated_set: []
nova::compute::cpu_shared_set: []
nova::compute::force_raw_images: true
nova::compute::image_cache::manager_interval: 2400
nova::compute::image_cache::precache_concurrency: 1
nova::compute::image_cache::remove_unused_base_images: true
nova::compute::image_cache::remove_unused_original_minimum_age_seconds: 86400
nova::compute::image_cache::remove_unused_resized_minimum_age_seconds: 3600
nova::compute::image_type_exclude_list: []
nova::compute::libvirt::cpu_mode: host-model
nova::compute::libvirt::cpu_model_extra_flags: ''
nova::compute::libvirt::cpu_models: []
nova::compute::libvirt::enabled_perf_events: []
nova::compute::libvirt::file_backed_memory: 0
nova::compute::libvirt::hw_machine_type: x86_64=q35
nova::compute::libvirt::log_filters: 1:libvirt 1:qemu 1:conf 1:security 3:event 3:json
  3:file 3:object 1:util
nova::compute::libvirt::log_outputs: 3:file:/var/log/libvirt/libvirtd.log
nova::compute::libvirt::manage_libvirt_services: false
nova::compute::libvirt::mem_stats_period_seconds: 10
nova::compute::libvirt::migration_support: false
nova::compute::libvirt::modular_libvirt: true
nova::compute::libvirt::num_pcie_ports: 16
nova::compute::libvirt::pmem_namespaces: ''
nova::compute::libvirt::preallocate_images: none
nova::compute::libvirt::qemu::configure_qemu: true
nova::compute::libvirt::qemu::max_files: 32768
nova::compute::libvirt::qemu::max_processes: 131072
nova::compute::libvirt::qemu::memory_backing_dir: ''
nova::compute::libvirt::rx_queue_size: 512
nova::compute::libvirt::services::libvirt_virt_type: kvm
nova::compute::libvirt::services::modular_libvirt: true
nova::compute::libvirt::swtpm_enabled: false
nova::compute::libvirt::tx_queue_size: 512
nova::compute::libvirt::virt_type: kvm
nova::compute::libvirt::virtlogd::log_filters: 1:logging 4:object 4:json 4:event 1:util
nova::compute::libvirt::virtlogd::log_outputs: 3:file:/var/log/libvirt/virtlogd.log
nova::compute::libvirt::virtnodedevd::log_filters: 1:qemu 1:libvirt 4:object 4:json
  4:event 1:util
nova::compute::libvirt::virtnodedevd::log_outputs: 3:file:/var/log/libvirt/virtnodedevd.log
nova::compute::libvirt::virtproxyd::log_filters: 1:qemu 1:libvirt 4:object 4:json
  4:event 1:util
nova::compute::libvirt::virtproxyd::log_outputs: 3:file:/var/log/libvirt/virtproxyd.log
nova::compute::libvirt::virtqemud::log_filters: 1:qemu 1:libvirt 4:object 4:json 4:event
  1:util
nova::compute::libvirt::virtqemud::log_outputs: 3:file:/var/log/libvirt/virtqemud.log
nova::compute::libvirt::virtsecretd::log_filters: 1:qemu 1:libvirt 4:object 4:json
  4:event 1:util
nova::compute::libvirt::virtsecretd::log_outputs: 3:file:/var/log/libvirt/virtsecretd.log
nova::compute::libvirt::virtstoraged::log_filters: 1:qemu 1:libvirt 4:object 4:json
  4:event 1:util
nova::compute::libvirt::virtstoraged::log_outputs: 3:file:/var/log/libvirt/virtstoraged.log
nova::compute::libvirt::vncserver_listen: '%{lookup(''internal_api'')}'
nova::compute::libvirt::volume_use_multipath: false
nova::compute::libvirt_guests::shutdown_timeout: '300'
nova::compute::live_migration_wait_for_vif_plug: true
nova::compute::max_disk_devices_to_attach: -1
nova::compute::mdev::mdev_types: {}
nova::compute::mkisofs_cmd: mkisofs
nova::compute::neutron_physnets_numa_nodes_mapping: {}
nova::compute::neutron_tunnel_numa_nodes: []
nova::compute::pci::passthrough: ''
nova::compute::provider::custom_inventories: {}
nova::compute::rbd::libvirt_images_rbd_ceph_conf: /etc/ceph/ceph.conf
nova::compute::rbd::libvirt_images_rbd_glance_copy_poll_interval: 15
nova::compute::rbd::libvirt_images_rbd_glance_copy_timeout: 600
nova::compute::rbd::libvirt_images_rbd_glance_store_name: default_backend
nova::compute::rbd::libvirt_images_rbd_pool: vms
nova::compute::rbd::libvirt_rbd_secret_key: AQDVs8NiAAAAABAA+DrFU9hak4TmkgwsXs/65w==
nova::compute::rbd::libvirt_rbd_secret_uuid: 0b7c7653-1501-450c-8dea-1da039e79371
nova::compute::rbd::libvirt_rbd_user: openstack
nova::compute::rbd::rbd_keyring: client.openstack
nova::compute::reserved_host_memory: 4096
nova::compute::reserved_huge_pages: []
nova::compute::resume_guests_state_on_host_boot: false
nova::compute::sync_power_state_interval: 600
nova::compute::use_cow_images: true
nova::compute::vcpu_pin_set: []
nova::compute::verify_glance_signatures: false
nova::compute::vgpu::vgpu_types_device_addresses_mapping: {}
nova::compute::vncproxy_host: openstack.bne-home.net
nova::compute::vncserver_proxyclient_address: '%{lookup(''internal_api'')}'
nova::cpu_allocation_ratio: 4.0
nova::db::database_db_max_retries: -1
nova::db::database_max_retries: -1
nova::dhcp_domain: ''
nova::disk_allocation_ratio: 0.0
nova::host: '%{lookup(''fqdn_canonical'')}'
nova::keystone::service_user::auth_url: http://192.168.1.25:5000
nova::keystone::service_user::password: QgE5gYRM5zaHlZDihVfa0tiyC
nova::keystone::service_user::project_name: service
nova::keystone::service_user::region_name: regionOne
nova::keystone::service_user::send_service_user_token: true
nova::logging::debug: false
nova::migration::libvirt::live_migration_inbound_addr: '%{lookup(''fqdn_internal_api'')}'
nova::migration::libvirt::live_migration_permit_auto_converge: true
nova::migration::libvirt::live_migration_permit_post_copy: true
nova::migration::libvirt::live_migration_tunnelled: false
nova::migration::libvirt::modular_libvirt: true
nova::migration::qemu::configure_qemu: true
nova::migration::qemu::migration_port_max: 61215
nova::migration::qemu::migration_port_min: 61152
nova::my_ip: '%{lookup(''internal_api'')}'
nova::network::neutron::auth_type: v3password
nova::network::neutron::auth_url: http://192.168.1.25:5000/v3
nova::network::neutron::ovs_bridge: br-int
nova::network::neutron::password: a1PIB0bVR8KCI5Nryq9ocVZeP
nova::network::neutron::project_name: service
nova::network::neutron::region_name: regionOne
nova::network::neutron::username: neutron
nova::network::neutron::valid_interfaces: internal
nova::notification_driver:
- noop
nova::notification_format: unversioned
nova::notify_on_state_change: vm_and_task_state
nova::os_region_name: regionOne
nova::ovsdb_connection: ''
nova::placement::auth_url: http://192.168.1.25:5000
nova::placement::password: vFwQ1AoetKNdWwCyrkEbcF6LS
nova::placement::project_name: service
nova::placement::region_name: regionOne
nova::placement::valid_interfaces: internal
nova::policy::enforce_new_defaults: false
nova::policy::enforce_scope: false
nova::policy::policies: {}
nova::policy::purge_config: true
nova::purge_config: false
nova::rabbit_heartbeat_in_pthread: false
nova::rabbit_heartbeat_timeout_threshold: 60
nova::rabbit_use_ssl: 'False'
nova::ram_allocation_ratio: 1.5
nova::rpc_response_timeout: 60
nova::vncproxy::common::vncproxy_host: openstack.bne-home.net
nova::vncproxy::common::vncproxy_port: '13080'
nova::vncproxy::common::vncproxy_protocol: https
nova::workarounds::disable_compute_service_check_for_ffu: false
nova::workarounds::never_download_image_if_on_rbd: false
nova_compute_opt_env_vars: {}
nova_compute_opt_volumes: []
nova_glance_enable_rbd_download: false
nova_glance_rbd_download_multistore_id: ''
nova_is_additional_cell: false
nova_libvirt_max_queues: 0
nova_libvirt_opt_volumes: []
nova_pmem_namespaces: ''
ovn::controller::hostname: '%{lookup(''fqdn_canonical'')}'
ovn::controller::ovn_bridge: br-int
ovn::controller::ovn_bridge_mappings:
- datacentre:br-ex
ovn::controller::ovn_cms_options: enable-chassis-as-gw
ovn::controller::ovn_encap_ip: '%{lookup(''tenant'')}'
ovn::controller::ovn_encap_type: geneve
ovn::controller::ovn_monitor_all: true
ovn::controller::ovn_openflow_probe_interval: 60
ovn::controller::ovn_remote_probe_interval: 60000
ovn::southbound::port: 6642
rbd_disk_cachemodes:
- network=writeback
rbd_persistent_storage: false
resume_guests_state_on_host_boot: false
snmp::agentaddress:
- udp:161
- udp6:[::1]:161
snmp::snmpd_options: -LS0-5d
tripleo::packages::enable_install: true
tripleo::profile::base::database::mysql::client::enable_ssl: false
tripleo::profile::base::database::mysql::client::mysql_client_bind_address: '%{lookup(''internal_api'')}'
tripleo::profile::base::database::mysql::client::ssl_ca: /etc/ipa/ca.crt
tripleo::profile::base::iscsid::chap_algs: SHA3-256,SHA256,SHA1,MD5
tripleo::profile::base::logging::logrotate::dateext: false
tripleo::profile::base::logging::logrotate::maxsize: 10M
tripleo::profile::base::logging::logrotate::purge_after_days: '14'
tripleo::profile::base::logging::logrotate::rotate: '14'
tripleo::profile::base::logging::logrotate::rotation: daily
tripleo::profile::base::neutron::container_cli: podman
tripleo::profile::base::neutron::ovn_metadata_agent_wrappers::debug: false
tripleo::profile::base::neutron::ovn_metadata_agent_wrappers::enable_haproxy_wrapper: true
tripleo::profile::base::neutron::ovn_metadata_agent_wrappers::haproxy_image: quay.io/tripleowallaby/openstack-neutron-metadata-agent-ovn:current-tripleo
tripleo::profile::base::neutron::ovn_metadata_agent_wrappers::haproxy_process_wrapper: /var/lib/neutron/ovn_metadata_haproxy_wrapper
tripleo::profile::base::nova::compute::cinder_nfs_backend: false
tripleo::profile::base::nova::compute::libvirt_guests::enabled: false
tripleo::profile::base::nova::compute::nova_nfs_enabled: false
tripleo::profile::base::nova::compute_libvirt_shared::nova_rbd_ceph_conf_path: /var/lib/tripleo-config/ceph
tripleo::profile::base::nova::libvirt::modular_libvirt: true
tripleo::profile::base::nova::migration::client::libvirt_enabled: true
tripleo::profile::base::nova::migration::client::nova_compute_enabled: true
tripleo::profile::base::nova::migration::client::ssh_port: 2022
tripleo::profile::base::nova::migration::client::ssh_private_key: '-----BEGIN PRIVATE
  KEY-----

  MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCj32BjI1IBocx+

  NEvcE0TToqCML2uvsjwT8cCFzmciHqL73rSo6Cvh+VSd/1mjynWJ8JG56BLtyy3f

  ND08P61Mdx53PFxM2hxMEyNqDPiqjF7NaVf2D6WTeWAUQbjV6f1m+eOG7WS+oO0a

  p8whcpNRek+DqSyHkp3INs5lROzwcZRRSyU2TD6WMyXvffQjQLAmopSjiJp+UyTJ

  MCT66o1JxGzIHTVrhRj7p4jX85+kqY3m9/sl4DkcJ6jaXtJip95yPNSwq5QWgfHM

  42SVjH2r8ge3YwwFtFN6LOmO3FXz8SsXXukeoRAQitjDMeHfmdxWSnDDYjt1uIA9

  oMjVhGMjAgMBAAECggEAR6K5dv0Ut0PsqergkpcVylJYTo/YSljm7G0NFTEyYnb0

  Fpi3bvL3Y/RjqiHbJL+3fBJfEd7Cj5L3PZCPiEvpzPhxp/wJ+UqLfjILlCuRdLSi

  KLd5TUZvwjUX7CMC0vhT3vU0ImKaXL7qh3F8yc5VWhPWuJ52qdlNAh37QcfMsBqy

  mzrVLmAvlG5YQtblzMSxW3DAECIPs8DpQNq/1x+K4fdY79ofj4scpp2t/FCTJ40d

  IhIDswdTfbez9vFvDWh49L9v9Bmm5IUgBc2NBIgRvDQPCDOo2mOHcLK2AZx1bgT8

  JnEv6CHWM4AUqFzVdxSZxrsTsEnZkAYdlCyQ+Wo4EQKBgQDiaIvEj6oI77Ai+9Yg

  N7DJmjWqzWh5/tFwRwN4hKbgWjwHeeIy2J3a/XExXspydwud2Iz+RzLSB7+5otJy

  v2Ki5f7tvsMmQtBA9o2S3XSROLTmvFfUiNXjVgeo4H9nmUggoKTGuRlbRS7EdyD+

  5i6uDm6cASdS7wEpEzyVgh6iqQKBgQC5Sm3cr6DuofI/Ed2rOtOfmPqsp4rZE4xr

  Q6tClWJVgPyY0X74uslS1WZZGYH3e3Hg33NKh6t6EVkmDMKtFdJp/mtOqoz2fRRv

  TZ0Av0bqD9bm4M1jzwC3kkuG7la4aes59BMauhUVowxMshAjNs5+bmrxMGBL+SQl

  RldSoLnC6wKBgBo+vjz53l8M0eEsSkUPz5l/G8uB5iOGK2cVhEx7LBEDxMOlGFiG

  jb3t9Sog79zW+ezBRo7PWA/KwCnXuwd8MgXqHWQX4e1Uf2mYaw7kRvfyl93LZW8I

  saqZtWeZJouu1BKcLJ2wpUTUPzidCqEhs7WPjLje1V0iwYKubS5zl/OJAoGBAIkD

  JXvTjtAGhofmoSB1zniseWhkN4LPNr02e5QvvFf3mlEyUI6CKE6NKDJobzdeW9Xp

  xWnuKnmIDIDbXLT6du4TyKuR58x4rzyiip870adQcRumTZopPqF/l0O+R/fzspHX

  Dq1rvh2SxIyN+urfIxBQe9m/aOWk4/qAKiAaY2JjAoGBAIexpJJbVTjCZmzA8YjN

  YcSrqL4GBY4whnwR2Tc9RcETNJoghvtHx7Bdw6z3L7Rk9VESwp/Vn5iigtHWJT90

  dAFNEsSeHRfx8zpfO33EVHlRK8/1kQvdxaivOqjtADhC5UlB1F+wW51tZNK2/gbJ

  EbrkLP5QaNh9I+uHt2AwaCVZ

  -----END PRIVATE KEY-----

  '
tripleo::profile::base::nova::migration::target::ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCj32BjI1IBocx+NEvcE0TToqCML2uvsjwT8cCFzmciHqL73rSo6Cvh+VSd/1mjynWJ8JG56BLtyy3fND08P61Mdx53PFxM2hxMEyNqDPiqjF7NaVf2D6WTeWAUQbjV6f1m+eOG7WS+oO0ap8whcpNRek+DqSyHkp3INs5lROzwcZRRSyU2TD6WMyXvffQjQLAmopSjiJp+UyTJMCT66o1JxGzIHTVrhRj7p4jX85+kqY3m9/sl4DkcJ6jaXtJip95yPNSwq5QWgfHM42SVjH2r8ge3YwwFtFN6LOmO3FXz8SsXXukeoRAQitjDMeHfmdxWSnDDYjt1uIA9oMjVhGMj
  Generated by TripleO
tripleo::profile::base::nova::virtlogd_wrapper::debug: false
tripleo::profile::base::nova::virtlogd_wrapper::enable_wrapper: true
tripleo::profile::base::nova::virtlogd_wrapper::virtlogd_image: quay.io/tripleowallaby/openstack-nova-libvirt:current-tripleo
tripleo::profile::base::nova::virtlogd_wrapper::virtlogd_process_wrapper: /var/lib/container-config-scripts/virtlogd_wrapper
tripleo::profile::base::snmp::snmpd_auth_type: MD5
tripleo::profile::base::snmp::snmpd_password: f0uHSRmpNG8MM0bebdKexm6t
tripleo::profile::base::snmp::snmpd_user: ro_snmp_user
tripleo::profile::base::sshd::listen:
- '%{lookup(''internal_api'')}'
- '%{lookup(''internal_api'')}'
tripleo::profile::base::sshd::options:
  AcceptEnv:
  - LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
  - LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
  - LC_IDENTIFICATION LC_ALL LANGUAGE
  - XMODIFIERS
  AllowTcpForwarding: 'no'
  AllowUsers: nova_migration
  AuthorizedKeysFile: .ssh/authorized_keys
  ChallengeResponseAuthentication: 'no'
  GSSAPIAuthentication: 'no'
  GSSAPICleanupCredentials: 'no'
  HostKey:
  - /etc/ssh/ssh_host_rsa_key
  - /etc/ssh/ssh_host_ecdsa_key
  - /etc/ssh/ssh_host_ed25519_key
  Subsystem: sftp  /usr/libexec/openssh/sftp-server
  SyslogFacility: AUTHPRIV
  UseDNS: 'no'
  UsePAM: 'yes'
  X11Forwarding: 'no'
tripleo::profile::base::sshd::password_authentication: 'no'
tripleo::profile::base::sshd::port:
- 2022
tripleo::trusted_cas::ca_map: {}
vhostuser_socket_group: qemu
vswitch::ovs::enable_hw_offload: false
